### PR TITLE
Handle CRI_TIMEOUT error

### PR DESCRIPTION
**Pull request by denar90**
Resolves problem with lighthouse `CriConnection:error` on CI.

### CODE REVIEW

**Comment by paulirish** [comment]
The runLighthouse function is pretty tangled. I'm having a hard time following the logic just reading it through, so maybe we can try another approach?

Perhaps break out an innerRunLighthouse to keep the retry logic separate from the actual calls to the lighthouse module?

**Comment by denar90** [comment]
Yeap it looks too complicated, I'll sit and think about simplification.

**Comment by paulirish** [comment]
@brendankenny did note that we've never needed this timeout stuff for anything other than travis.  So if that's helpful we could try to isolate this and only do it in the travis case...

**Comment by denar90** [comment]
Yeap, lets go this way.

**Comment by paulirish** [comment]
yah. much happier with this. thanks!

**Pull request merged**
