### PR TITLE
Add eslint rules…

### PR DESCRIPTION
**Pull request by pedro93**
To have some linting rules in the repository, response to: https://github.com/paulirish/pwmetrics/issues/43

125 problems to be solved (no-undef, rest params and max-length errors) need help...

@denar90 @paulirish This is not yet ready but if either of you know how to solve the remaining problems I would love some help, this is beyond my knowledge 😝 . Perhaps we can merge to master and we finish it together?

### CODE REVIEW

**Comment by denar90** [comment]
Since we have a lot of eslint errors I have an idea. What if we merge eslint and stuff around it with commented rules for eslint config in scope of this pr?
Then step by step, uncommenting rule by rule fixing issues.
Profit from this approach: reduced number of possible merge conflicts, easier to fix them (easier to fix 10 small issue the 1 big :) )

**Comment by pedro93** [comment]
I like it :) I can fix the merge conflicts and comment out the rules. Then we merge it and fix incrementally.

**Comment by paulirish** [comment]
does `--fix` get us very far?  but yeah agree that right now it's a little tricky because conflicts.

we could set most of the errors to warnings and land it like that.

**Comment by pedro93** [comment]
I didn't know about that flag, I manually went into each file and used vscode's integration with eslint, it didn't solve those though. The PR already sets the warning. May I suggest we merge it and fix the warnings post-PR?

**Comment by paulirish** [comment]
Sgtm

**Pull request merged**
