### PR TITLE
add new image

### PR DESCRIPTION
**Pull request by denar90**
Thoughts?

P.S. Feel free to criticize it!

### CODE REVIEW

**Comment by pedro93** [comment]
Very nice 👍

**Comment by paulirish** [comment]
Hah! very cool.

I think we should keep the screenshot and a logo separate things.  :)

I do like the general concept of the logo you made here, but we could probably tighten it up, and drop the text. something smaller like 450x230 or whatever.

So let's iterate on the image, and we can refresh the screenshot with a newer version sometime too. :)

**Comment by denar90** [comment]
Thanks guys :)

**Comment by denar90** [comment]
Here is a new one. 
We can also can involve @samccone if he don't mind 😛 

pwmetrics-small

**Comment by samccone** [comment]
I think it is cool ;)

**Comment by paulirish** [comment]
yup. i dig the new one. :)

**Pull request merged**
