### PR TITLE
[RFC] Consider Wunderbar

### PR DESCRIPTION
**Pull request by gribnoysup**
A follow-up to https://github.com/paulirish/pwmetrics/issues/157#issuecomment-374679877

Feel free to close it if you are not convinced 😸

### CODE REVIEW

**Comment by denar90** [comment]
I've created new branch `version-4` and change base. This one can be merged If noone against of this solution :)

**Comment by gribnoysup** [comment]
@denar90 perfect timing, haha! I just pushed a few smallish updates:

- Windows compat issues are resolved in the Wunderbar; Bumped dependency version
- Removed charm completely: it is not used anywhere in the PWMetrics anymore
- Updated yarn.lock file; COmpletely missed it the first time 😅

**Comment by pedro93** [comment]
One question: After this is merged what version will pwmetrics bump to? It should be a minor version right? No breaking functionality was introduced right?

**Comment by denar90** [comment]
It isn't breaking change, but what I wanted is more cool stuff in version 4. Not just LH update, it will be boring for users. If we present LH update, wunderbar and others then it will be more attractive, at list I think...

**Comment by paulirish** [comment]
TBH I don't know if pwmetrics gets a lot of new benefit out of LH 3.0. So it does seem reasonable to do a minor release with the wunderbar stuff.

**Comment by denar90** [comment]
Merged 💥 @gribnoysup thanks for your effort 💪

**Comment by gribnoysup** [comment]
Yay! Thank you all! I'm glad I could be of any help to this project 😸

**Pull request merged**
