### PR TITLE
Improve config to get TTCI and TTFI results

### PR DESCRIPTION
**Pull request by denar90**
Solves so many problems (https://github.com/GoogleChrome/lighthouse/issues/2801, #148 and others). Huge thanks to @patrickhulce.

### CODE REVIEW

**Comment by pedro93** [comment]
LGTM! :)

**Comment by paulirish** [comment]
cc @patrickhulce

**Comment by paulirish** [comment]
oh nvm!

**Comment by denar90** [comment]
merging?

**Comment by pedro93** [comment]
I don't see any downside. It will make pwmetric runs slower but the results will be less flaky/more consistent, so from me, yes merge.

**Comment by denar90** [comment]
done 🎉

**Pull request merged**
