### PR TITLE
Update Chrome-launcher to v0.2.0 and test runner

### PR DESCRIPTION
**Pull request by pedro93**
- Updates chrome-launcher to 0.2.0 to remove package's dependency on lighthouse, for faster install times.
- Updates test-runner.sh to work with node version 8 and greater.
- Adds package-lock file to ensure exact version reproducibility.

### CODE REVIEW

**Comment by pedro93** [comment]
Do not merge, waiting to see if chrome-launcher changes due to https://github.com/GoogleChrome/lighthouse/issues/2568

**Comment by paulirish** [comment]
chrome-launcher@0.2.1 shipped with updated deps

**Comment by pedro93** [comment]
Package.lock.json was auto-generated with npm v5, it offers reproducibility like yarn I think. I've removed it.

**Comment by paulirish** [comment]
pwmetrics 3.0.1 shipped with this

**Pull request merged**
